describe("public API", function()
  it("loads and exposes inactive status", function()
    local code_review = require("code-review")
    code_review.setup({})
    assert.is_false(code_review.is_active())
    assert.equals("", code_review.status())
  end)

  it("registers commands idempotently", function()
    local code_review = require("code-review")
    code_review.setup({})
    code_review.setup({})
    assert.truthy(vim.api.nvim_get_commands({})["CodeReview"])
    assert.truthy(vim.api.nvim_get_commands({})["CodeReviewHealth"])
    assert.truthy(vim.api.nvim_get_commands({})["CodeReviewClearData"])
  end)

  it("uses parent-prefix keymap defaults", function()
    local cfg = require("code-review.config")
    cfg.setup({})
    assert.equals("<leader>r", cfg.get().keymaps.prefix)
    assert.equals("r", cfg.get().keymaps.open_picker)
  end)
end)
