describe("debouncing", function()
  it("debounces storage persistence after dirty marks", function()
    local config = require("code-review.config")
    local storage = require("code-review.storage")
    local root = vim.fn.tempname()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(root, "p")
    vim.fn.mkdir(dir, "p")
    config.setup({ storage = { dir = dir, debounce_ms = 30 } })
    local handle = storage.load(root)
    storage.mark_dirty(handle)
    assert.equals(0, vim.fn.filereadable(handle.path))
    vim.wait(200, function()
      return vim.fn.filereadable(handle.path) == 1
    end)
    assert.equals(1, vim.fn.filereadable(handle.path))
  end)
end)
